### ISSUE TITLE
大佬 我部署了这个项目 但是生成出来的链接访问是404

### ISSUE THREAD

**Issue by wxDadadada** [BarryYangi/ee#1]
![image](https://github.com/user-attachments/assets/8194bc45-624b-444b-872f-9be346f57e5d)
这种会是什么原因呀

**Comment by wxDadadada** [comment]
贴一下生成的链接：[https://ee-kappa-one.vercel.app/eeeeеɵɵeеөеeеөеeеөeeеөeөeөɵɵeɵөөeɵөөеөеөеɵеееɵɵееɵeɵеɵөөeɵөɵеɵeөеɵөөеɵөе](https://ee-kappa-one.vercel.app/eeee%D0%B5%C9%B5%C9%B5e%D0%B5%D3%A9%D0%B5e%D0%B5%D3%A9%D0%B5e%D0%B5%D3%A9ee%D0%B5%D3%A9e%D3%A9e%D3%A9%C9%B5%C9%B5e%C9%B5%D3%A9%D3%A9e%C9%B5%D3%A9%D3%A9%D0%B5%D3%A9%D0%B5%D3%A9%D0%B5%C9%B5%D0%B5%D0%B5%D0%B5%C9%B5%C9%B5%D0%B5%D0%B5%C9%B5e%C9%B5%D0%B5%C9%B5%D3%A9%D3%A9e%C9%B5%D3%A9%C9%B5%D0%B5%C9%B5e%D3%A9%D0%B5%C9%B5%D3%A9%D3%A9%D0%B5%C9%B5%D3%A9%D0%B5)

**Comment by BarryYangi** [comment]
https://x.yct.ee/eeeLink

这个服务有后端的，可以参考我这篇文章去cf上搭建一下

**Comment by wxDadadada** [comment]
ok 感谢大佬 已成功运行
